defaults:
  - losses@loss_mapping.pairwise_l2_loss: pairwise_l2_loss
  - losses@loss_mapping.l2_loss: l2_loss
  - losses@loss_mapping.ligand_pairwise_l2_loss: ligand_pairwise_l2_loss
  - losses@loss_mapping.ligand_l2_loss: ligand_l2_loss
  - losses@loss_mapping.rg_loss: rg_loss
  - losses@loss_mapping.sasa_loss: sasa_loss
  
_target_: lobster.model.latent_generator.latent_generator.tokenizer.LossFactory.from_mapping
weight_dict:
  pairwise_l2_loss: 1.0
  l2_loss: 0.01
  ligand_pairwise_l2_loss: 1.0
  ligand_l2_loss: 0.01
  rg_loss: 0.1
  sasa_loss: 0.1