_target_: lobster.model.latent_generator.latent_generator.structure_decoder.ViTDecoder
data_fixed_size: 512
n_atoms: 3
uvit_n_layers: 6
uvit_n_heads: 8
uvit_dim_head: 32
uvit_position_embedding_type: 'rotary'
indexed: false
struc_token_dim: 512
struc_token_codebook_size: 256
