throughput:
  _target_: lightning.pytorch.callbacks.ThroughputMonitor
  batch_size_fn: 
    _target_: lobster.callbacks.throughput_batch_size_fn
  length_fn:
    _target_: lobster.callbacks.throughput_length_fn