# @package _global_
hydra:
    sweeper:
        params:
            data_folder: "/data/bucket/ismaia11/affinity/data/"
            train_data: affinity_round_train_r10.csv
            val_data: affinity_val_r10.csv
            test_data: s3://prescient-data-dev/leaderboards/testsets/round_9/binders.parquet
            checkpoints: '/data/bucket/ismaia11/affinity/checkpoints_new/'
            results_dir: '/data/bucket/ismaia11/affinity/results/'
            output_dir: '/data/bucket/ismaia11/affinity/output/esm/'
            train: False
            patience: 1000
            epochs: 50
            batch_size: 64
            itr:  1
            scale: false
            task: classification
            is_binary: true
            use_multi_gpu: true
            target_value: 'affinity_is_binder_pkd_4'
            wd: 1.8137891736510614e-05
            lr: 5.e-5
            model: esm2_t30_150M_UR50D
            init_step: false
            path_for_init: ""
            vh_seq: 'fv_heavy_aho'
            vl_seq: 'fv_light_aho'
            target_seq: 'affinity_antigen'
            ++wandb.name: 'esm2_roundOnly'
            append: '_roundOnly'
            ++wandb.project: 'r10'
