# @package _global_
hydra:
    sweeper:
        params:
            data_folder: "/data/bucket/ismaia11/affinity/data/"
            train_data: affinity_round_train_r10.csv
            val_data: affinity_val_r10.csv
            test_data: s3://prescient-data-dev/leaderboards/testsets/round_9/binders.parquet
            checkpoints: '/data/bucket/ismaia11/affinity/checkpoints/'
            results_dir: '/data/bucket/ismaia11/affinity/results/'
            output_dir: '/data/bucket/ismaia11/affinity/output/esm/'
            train: true
            patience: 100
            use_moe: true
            epochs: 50
            batch_size: 128
            itr:  1
            scale: false
            task: classification
            is_binary: true
            use_multi_gpu: true
            target_value: 'affinity_is_binder_pkd_4'
            wd: 1.8137891736510614e-05
            num_experts: 5
            gate_type: MLP
            expert_type: MLP
            lr: 5.e-5
            utilization_hp: 1.0
            model: esm2_t30_150M_UR50D
            start_epoch: 18
            load_checkpoint: true
            checkpoint_path: '/data/bucket/ismaia11/affinity/checkpoints/Affinity_esm2_t30_150M_UR50D_MoE_MLP_FT_bs128_LE_lr5e-05_classification__roundOnly_0_last.pth'
            init_step: false
            path_for_init: ""
            vh_seq: 'fv_heavy_aho'
            vl_seq: 'fv_light_aho'
            target_seq: 'affinity_antigen'
            ++wandb.name: 'esm2_moe_roundOnly'
            append: '_roundOnly'
            ++wandb.project: 'r10'
