dssp_linear_probe:
  _target_: lobster.model.latent_generator.callbacks.DSSPLinearProbe
  # Model parameters
  token_dim: 256  # Dimension of the learned tokens
  # Data paths
  train_paths: None
  val_paths: None
  # Training parameters
  learning_rate: 1
  weight_decay: 1e-4
  batch_size: 500
  run_every_n_steps: 1000
  save_every_n: 20000  # Save predictions every N batches
  num_epochs: 100  # Maximum number of epochs to train the probe
  patience: 10  # Number of epochs to wait for improvement before early stopping
  min_delta: 0.001  # Minimum change in validation accuracy to be considered as improvement
