model_checkpoint_val:
  _target_: "lightning.pytorch.callbacks.ModelCheckpoint"
  dirpath: "${hydra:runtime.output_dir}/checkpoints"
  save_top_k: 3
  save_last: true
  monitor: "val_loss"
  every_n_train_steps: 1000
