defaults:
  - _self_
  - experiment: null
  # - wandb: ismail-aya

# TODO jwp: nest keys for better organization
oracle: Affinity
data_folder: "/data/bucket/ismaia11/affinity/data/"
train_data: binding_quantized_affinity_r7_tune_2022-12-08_train.csv
val_data: binding_quantized_affinity_r7_tune_2022-12-08_iid_val.csv
test_data: binding_quantized_affinity_r5_r6_lab_loop.csv
calculate_rmse: true
problem: 'affinity'
use_gpu: true
patience: 20
batch_size: 32
num_workers: 4
lr: 2.3864193773088247e-05
wd: 1.8137891736510614e-05
epochs: 100
model: esm1b_t6
use_multi_gpu: false
use_augmentation: true
use_augmentation_test: true
use_training_for_val: false
itr: 1
gpu: 0
devices: '0,1,2,3'
scale: true
is_binary: true
task: regression
plot: false
append: ""
output_dir: './outputs/'
results_dir: './results/'
checkpoints: ''
pretrained_path: ''
num_experts: 7
expert_type: Linear
gate_type: Linear
accuracy_hp: 1.0
utilization_hp: 1.0
floor_predictions: false
init_step: true
path_for_init: ""
seed: 123
train: true
checkpoint_path: null
feature_token: 'mean'
use_moe: false
basied_model_path: ''
save_name: ''
tags: ~
command: ~
shard_num: ~
vh_seq: 'fv_heavy'
vl_seq: 'fv_light'
target_seq: 'target_seq'
target_value: 'pKD'
aux_target_value: ''
source: []
is_binder: 'is_binder'
preprocess: LE
load_pretrained: false
load_checkpoint: false
single_run_dir: ${hydra:run.dir}
emb_dim: 10
d_model: 128
n_layers: 3
training_type: 'regular'
add_noise: false
rand_smooth_noise_multiplier: 0
plot_saliency: false
plot_saliency_num: 0
plot_dir: './plot/'
remove_ds: []
start_epoch: 0
temp: 0.07
use_mlp: true
