defaults:
  - decoders@decoder_mapping.vit_decoder: vit_decoder
  - decoders@decoder_mapping.c6d_decoder: c6d_decoder

_target_: lobster.model.latent_generator.latent_generator.structure_decoder.DecoderFactory.from_mapping
decoder2loss_dict:
  vit_decoder: [l2_loss, pairwise_l2_loss]
  c6d_decoder: [c6d_loss]