defaults:
  - decoders@decoder_mapping.vit_decoder: vit_decoder
  - decoders@decoder_mapping.foldseek3di_decoder: foldseek3di_decoder

_target_: lobster.model.latent_generator.latent_generator.structure_decoder.DecoderFactory.from_mapping
decoder2loss_dict:
  vit_decoder: [l2_loss, pairwise_l2_loss]
  foldseek3di_decoder: [cce_loss]