_target_: lobster.model.gen_ume.UMESequenceStructureEncoderLightningModule 
lr: 1e-4
scheduler: constant_with_warmup
scheduler_kwargs:
  num_warmup_steps: 10_000
num_warmup_steps: 20_000
num_training_steps: 100_000
weight_decay: 0.01
mask_token_id: 8
pad_token_id: 6
vocab_size: 33
special_token_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
ckpt_path: null
encoder_kwargs:
  max_length: ${data.max_length}
  model_size: mini