
_target_: lobster.model.latent_generator.tokenizer.TokenizerMulti

ckpt_path: null

structure_encoder:
  _target_: lobster.model.latent_generator.structure_encoder.ViTEncoder
  data_fixed_size: 512
  n_atoms: 3
  model_n_channel: 20
  uvit_n_layers: 6
  uvit_n_heads: 8
  uvit_dim_head: 32
  uvit_position_embedding_type: 'rotary'
  embed_dim: 4
  embed_dim_hidden: 256
  backbone_noise: 0.00 #0.30
  concat_sine_pw: true
  encode_ligand: false
  ligand_atom_embedding: false

quantizer:
  _target_: lobster.model.latent_generator.quantizer.LigandTokenizer
  n_tokens: 256
  gumbel: true
  tau: 0.5
  embed_dim: 256
  ligand_n_tokens: 256
  ligand_embed_dim: 256
  ligand_softmax: false
  ligand_emb_noise: 0.0
  ligand_gumbel: true
  ligand_use_gumbel_noise: true
  ligand_tau: 0.5

decoder_factory:
  _target_: lobster.model.latent_generator.structure_decoder.DecoderFactory.from_mapping
  decoder2loss_dict:
    vit_decoder: [l2_loss, pairwise_l2_loss, ligand_l2_loss, ligand_pairwise_l2_loss]
  decoder_mapping:
    vit_decoder: 
      _target_: lobster.model.latent_generator.structure_decoder.ViTDecoder
      data_fixed_size: 512
      n_atoms: 3
      uvit_n_layers: 6
      uvit_n_heads: 8
      uvit_dim_head: 32
      uvit_position_embedding_type: 'rotary'
      indexed: false
      struc_token_dim: 512
      struc_token_codebook_size: 256
      encode_ligand: false

loss_factory:
  _target_: lobster.model.latent_generator.tokenizer.LossFactory.from_mapping
  weight_dict:
    pairwise_l2_loss: 1.0
    l2_loss: 0.01
    ligand_pairwise_l2_loss: 1.0
    ligand_l2_loss: 0.01
  loss_mapping:
    pairwise_l2_loss:
      _target_: lobster.model.latent_generator.tokenizer.PairWiseL2Loss
    l2_loss:
      _target_: lobster.model.latent_generator.tokenizer.L2Loss
    ligand_pairwise_l2_loss:
      _target_: lobster.model.latent_generator.tokenizer.LigandPairWiseL2Loss
    ligand_l2_loss:
      _target_: lobster.model.latent_generator.tokenizer.LigandL2Loss

optim:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

num_warmup_steps: 5000
num_training_steps: 50000

lr_scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 5000
  num_training_steps: 50000




