_target_: lobster.model.modern_bert.FlexBERT

# Base model parameters
lr: 1e-3
num_training_steps: ${trainer.max_steps}
model_name: UME_mini
num_warmup_steps: 10_000
max_length: 512
mask_percentage: 0.25
scheduler: "constant_with_warmup"

# Model-specific configuration parameters
model_kwargs:
  embedding_layer: linear_pos 
  hidden_act: gelu

# Scheduler-specific configuration parameters
scheduler_kwargs:
  # Any specific scheduler parameters would go here
  # For example:
  # min_lr: 1e-7  # For cosine_with_min_lr scheduler


ckpt_path: null # unused, for compatibility with lobster_train