_target_: lobster.model.UME
model_name: UME_small
lr: 4e-4
beta1: 0.9
beta2: 0.98
eps: 1e-12
num_training_steps: ${trainer.max_steps}
num_warmup_steps: 1_000
mask_percentage: 0.25
max_length: 512
model_kwargs: 
  unpad_embeddings: true
ckpt_path: null 
weight_decay: 0.01