# Example configuration for forward folding (structure generation from input sequences and structures)
# Forward folding takes input structures and their sequences, then generates new structures
# Sequences are automatically tokenized using AminoAcidTokenizerTransform
# Usage: uv run python -m lobster.cmdline.generate --config-path "/homefs/home/lisanzas/scratch/Develop/lobster/examples" --config-name generate_forward_folding

# Output directory
output_dir: "./examples/generated_forward_folding"

# Random seed for reproducibility
seed: 54321

# Model configuration
model:
  _target_: lobster.model.gen_ume.UMESequenceStructureEncoderLightningModule
  ckpt_path: "/data2/ume/gen_ume/runs//2025-10-08T23-54-39/last.ckpt"  # Update this path

# Generation settings
generation:
  mode: forward_folding
  nsteps: 800          # More steps for forward folding
  batch_size: 1        # Process 2 structures at a time
  n_trials: 1          # Number of trials for best output selection
  
  #Generation parameters
  temperature_seq: 0.5317880918477355    
  temperature_struc: 0.16001042166543197  
  stochasticity_seq: 20 
  stochasticity_struc: 60
  
  # Input structures - update these paths to your structure files
  # Examples of different input formats:
  # Single file: input_structures: "/path/to/structure.pdb"
  # Directory: input_structures: "/path/to/structure/directory/"
  # Glob pattern: input_structures: "/path/to/structures/*.pdb"
  # List of files: input_structures: ["/path/to/file1.pdb", "/path/to/file2.pdb"]
  input_structures: "/data2/lisanzas/multi_flow_data/test_set_filtered_pt/*.pt"
  
  # Maximum length for structures
  max_length: 512
  
  # Not used for forward folding
  length: null
  num_samples: null
