defaults:
  - sampler: randomized_minority_upsampler.yaml # Dataloader batch sampler
  - transforms: structure_backbone_transform.yaml # Dataset transforms
  - collate_fn: collate_fn_backbone_binder_target.yaml # Collate function for the dataloader

_target_: lobster.model.latent_generator.datamodules.StructureLightningDataModule
root: /data/lisanzas/structure_tokenizer/studies/data/pinder/processed_atom/pdb/all/temp/ # this doesnt do anything
path_to_datasets: ["/data2/lisanzas/latent_generator_files/afdb_data/processed_pt/train_afdb_genie2_data.pt", "/data2/lisanzas/latent_generator_files/pdb_data/split_data/validation.pt", "/data2/lisanzas/latent_generator_files/pdb_data/split_data/test.pt"]
max_length: 512 # Maximum length of the sequence; not used
cluster_file: null
files_to_keep: null # this doesnt do anything
testing: false
use_shards: false

# Dataloader Params
batch_size: 20 # Batch size for the dataloader
num_workers: 12 # Number of workers for the dataloader
