defaults:
  - transforms: structure_with_3di_transform.yaml # Dataset transforms
  - ligand_transforms: structure_ligand_transform.yaml

_target_: lobster.model.latent_generator.datamodules.StructureLightningDataModule
root: /data/lisanzas/structure_tokenizer/studies/data/pinder/processed_atom/pdb/all/temp/ # this doesnt do anything
path_to_datasets: ["/data/bucket/lisanza/structures/pdb_bind/processed_2/"]
max_length: 512 # Maximum length of the sequence; not used
cluster_file: null
files_to_keep: null
use_ligand_dataset: true
testing: false

# Dataloader Params
batch_size: 40 # Batch size for the dataloader
num_workers: 12 # Number of workers for the dataloader
