# Test configuration for small runs
defaults:
  - config

# Override for testing
test_mode: true
test_sizes: [500, 100, 100]
max_molecules: null
overwrite_parquet: true
overwrite_ds: true
percentile_threshold: 10.0
output_dir: ${data_dir}/cache/qm9_pairs_test 