# Model evaluation configuration

output_dir: ${hydra:runtime.cwd}/evaluation_results
datamodule:
  _target_: lobster.evaluation._dummy.DummyLightningDataModule


model:
  _target_: lobster.evaluation._dummy.DummyLightningModule
  # model_path: /path/to/model.pt

callbacks:
  - _target_: lobster.callbacks.CalmLinearProbeCallback
    max_length: 128
    tasks: [meltome, solubility]  
    batch_size: 8
  
  - _target_: lobster.callbacks.MoleculeACELinearProbeCallback
    max_length: 128
    batch_size: 8
  
  - _target_: lobster.callbacks.PEEREvaluationCallback
    max_length: 128
    tasks: [stability, solubility]
    batch_size: 8
  
  - _target_: lobster.callbacks.UmapVisualizationCallback
    output_dir: umap
    group_by: dataset
    max_samples: 100
  
