
output_dir: evaluation_reports
batch_size: 16
max_samples: 1000
find_closest_checkpoints: false # Find checkpoints that are closest in terms of training steps (multiple model evaluation)
find_evenly_spaced: true # Find checkpoints that are evenly spaced in terms of training steps (single model evaluation)

models:
  Ume-mini: ???
  Ume-small: ???
  Ume-medium: ???
  Ume-large: ???
