# Model evaluation configuration
# To run:

# lobster_eval model.model_path=path_to_your_checkpoint.ckpt

output_dir: ${hydra:runtime.cwd}/evaluation_results/${now:%Y-%m-%d_%H-%M-%S}

datamodule:
  _target_: lobster.data.UmeLightningDataModule
  tokenizer_max_length: 8192

model:
  _target_: lobster.model.Ume
  model_path: ???

callbacks:
  - _target_: lobster.callbacks.CalmLinearProbeCallback
    max_length: 128
    tasks: [meltome, solubility]  
    batch_size: 8
  
  - _target_: lobster.callbacks.MoleculeACELinearProbeCallback
    max_length: 128
    batch_size: 8
    tasks: [CHEMBL234_Ki]
  
  - _target_: lobster.callbacks.PEEREvaluationCallback
    max_length: 128
    tasks: [stability, solubility]
    batch_size: 8
  
  - _target_: lobster.callbacks.UmapVisualizationCallback
    output_dir: ${output_dir}/umap
    group_by: null
    max_samples: 100
  
