trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: auto
  num_nodes: 1
  accumulate_grad_batches: 16
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  precision: 32
  max_steps: 250000
  val_check_interval: 1000
  limit_val_batches: 10
  num_sanity_val_steps: 0
  max_time: null
  max_epochs: -1 