"""Back-compat shim for the reward terms, moved to :mod:`plm_design_rl.rewards`.

The reward oracles and shaping terms now live in the standalone ``plm_design_rl``
package. This module re-exports the identical public surface at the old import path so
existing code (``from lobster.rl_training.rewards import chainbreak_reward`` etc.) keeps
working unchanged. The worker-pool client :class:`ShapeRewardClient` /
:func:`reward_from_shape` moved to :mod:`plm_design_rl.pool` and is re-exported here too
to preserve the historical namespace. Individual ``._X`` submodule paths are aliased by
their own shim files.
"""

from plm_design_rl.pool import ShapeRewardClient, reward_from_shape
from plm_design_rl.rewards import (
    DEFAULT_CONF_WEIGHTS,
    INVALID_3DI_STATE,
    SFT_IGNORE_INDEX,
    ProtenixRewardClient,
    aar_terms,
    assemble_structure_expert,
    binder_clash_terms,
    binder_letters_to_aa33,
    binder_selfclash,
    build_struct_sft_targets,
    chainbreak_reward,
    clash_contact_reward,
    cloud_from_atom14,
    combined_distribution_terms,
    confidence_components,
    continuous_ip,
    coverage,
    derive_3di_tokens,
    derive_structure_tokens,
    design_hists_scoped,
    design_interface_hists,
    distribution_terms,
    hamming_novelty_group,
    interface_allatom_clash,
    interface_residue_mask,
    jaccard_novelty_group,
    js,
    kabsch,
    kmer_jaccard,
    lc_floor_penalty,
    lc_saturating_reward,
    linguistic_complexity,
    load_reference_table,
    passes,
    ddg_packed_all,
    ddg_per_binder_residue,
    ddg_reward,
    ddg_terms,
    reference_for,
    reward_from_aar,
    reward_from_confidence,
    rog_compactness,
    rog_compactness_reward,
    sc_clash_reward,
    shape_complementarity_reward,
    shape_complementarity_reward_atoms,
    structure_expert_from_cif,
    structure_terms,
    tm_score,
    tv,
)

__all__ = [
    "DEFAULT_CONF_WEIGHTS",
    "ProtenixRewardClient",
    "confidence_components",
    "continuous_ip",
    "passes",
    "reward_from_confidence",
    "kabsch",
    "structure_terms",
    "tm_score",
    "coverage",
    "hamming_novelty_group",
    "jaccard_novelty_group",
    "kmer_jaccard",
    "lc_floor_penalty",
    "lc_saturating_reward",
    "linguistic_complexity",
    "combined_distribution_terms",
    "design_hists_scoped",
    "design_interface_hists",
    "distribution_terms",
    "js",
    "load_reference_table",
    "reference_for",
    "tv",
    "clash_contact_reward",
    "chainbreak_reward",
    "rog_compactness",
    "rog_compactness_reward",
    "binder_clash_terms",
    "binder_selfclash",
    "cloud_from_atom14",
    "interface_allatom_clash",
    "sc_clash_reward",
    "aar_terms",
    "binder_letters_to_aa33",
    "interface_residue_mask",
    "reward_from_aar",
    "SFT_IGNORE_INDEX",
    "shape_complementarity_reward",
    "shape_complementarity_reward_atoms",
    "ddg_packed_all",
    "ddg_per_binder_residue",
    "ddg_reward",
    "ddg_terms",
    "ShapeRewardClient",
    "reward_from_shape",
    "INVALID_3DI_STATE",
    "assemble_structure_expert",
    "build_struct_sft_targets",
    "derive_3di_tokens",
    "derive_structure_tokens",
    "structure_expert_from_cif",
]
