name: Build and Release DXT Extension

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering for testing
    inputs:
      version:
        description: 'Version to build (e.g. v0.1.0-test)'
        required: true
        default: 'v0.1.0-test'

jobs:
  build-dxt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv sync --extra mcp
        
    - name: Build DXT extension
      run: |
        python scripts/build_dxt.py
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: lobster.dxt
        draft: false
        prerelease: ${{ github.event_name == 'workflow_dispatch' }}
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Release ${{ github.event.inputs.version || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 